-- Chạy toàn bộ đoạn này trong Supabase > SQL Editor

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  order_date date not null,
  dish_name text not null,
  unit_price numeric(12,0) not null check (unit_price >= 0),
  quantity integer not null default 1 check (quantity between 1 and 20),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists orders_order_date_idx
on public.orders(order_date);

alter table public.orders enable row level security;

drop policy if exists "anon_can_read_orders" on public.orders;
create policy "anon_can_read_orders"
on public.orders
for select
to anon
using (true);

drop policy if exists "anon_can_insert_orders" on public.orders;
create policy "anon_can_insert_orders"
on public.orders
for insert
to anon
with check (true);

drop policy if exists "anon_can_delete_orders" on public.orders;
create policy "anon_can_delete_orders"
on public.orders
for delete
to anon
using (true);

grant select, insert, delete on table public.orders to anon;
grant usage, select on sequence public.orders_id_seq to anon;


CREATE TABLE IF NOT EXISTS menu_items (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    dish_name TEXT UNIQUE NOT NULL,
    price NUMERIC(12,0) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO menu_items (dish_name, price)
VALUES
('Cơm gà',40000),
('Cơm sườn',45000),
('Cơm cá',40000),
('Cơm chay',35000),
('Bún bò',45000)
ON CONFLICT DO NOTHING;


-- ==========================================================
-- POLICY CHO BẢNG menu_items KHI ĐÃ BẬT RLS
-- Chạy toàn bộ trong Supabase > SQL Editor > New Query > Run
-- ==========================================================

alter table public.menu_items enable row level security;

drop policy if exists "anon_read_menu_items" on public.menu_items;
create policy "anon_read_menu_items"
on public.menu_items
for select
to anon
using (true);

drop policy if exists "anon_insert_menu_items" on public.menu_items;
create policy "anon_insert_menu_items"
on public.menu_items
for insert
to anon
with check (true);

drop policy if exists "anon_update_menu_items" on public.menu_items;
create policy "anon_update_menu_items"
on public.menu_items
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_menu_items" on public.menu_items;
create policy "anon_delete_menu_items"
on public.menu_items
for delete
to anon
using (true);

grant select, insert, update, delete
on table public.menu_items
to anon;

grant usage, select
on sequence public.menu_items_id_seq
to anon;


-- ==========================================================
-- TẠO BẢNG THÀNH VIÊN + RLS POLICY
-- Chạy toàn bộ trong Supabase > SQL Editor > New Query > Run
-- ==========================================================

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  full_name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Thêm các tên đang dùng hiện tại
insert into public.members (full_name, active)
values
('Nguyễn Quang Trung', true),
('Nguyễn Văn Sáng', true),
('Huỳnh Thanh Quảng', true)
on conflict (full_name) do nothing;

alter table public.members enable row level security;

drop policy if exists "anon_read_members" on public.members;
create policy "anon_read_members"
on public.members
for select
to anon
using (true);

drop policy if exists "anon_insert_members" on public.members;
create policy "anon_insert_members"
on public.members
for insert
to anon
with check (true);

drop policy if exists "anon_update_members" on public.members;
create policy "anon_update_members"
on public.members
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_members" on public.members;
create policy "anon_delete_members"
on public.members
for delete
to anon
using (true);

grant select, insert, update, delete
on table public.members
to anon;

grant usage, select
on sequence public.members_id_seq
to anon;



-- ==========================================================
-- THÊM TRẠNG THÁI CHỜ GIAO / ĐÃ GIAO CHO ĐƠN HÀNG
-- Chạy 1 lần trong Supabase > SQL Editor > New Query > Run
-- ==========================================================

alter table public.orders
add column if not exists status text not null default 'Chờ giao';

-- Chuẩn hóa các dòng cũ nếu cần
update public.orders
set status = 'Chờ giao'
where status is null or status not in ('Chờ giao', 'Đã giao');

-- RLS: cho phép cập nhật trạng thái bằng publishable/anon key
drop policy if exists "anon_update_orders" on public.orders;

create policy "anon_update_orders"
on public.orders
for update
to anon
using (true)
with check (true);

grant update on table public.orders to anon;



-- V18: thêm link ảnh cho từng món
alter table public.menu_items
add column if not exists image_url text;

-- Không bắt buộc nhập ảnh. Nếu để trống, ứng dụng sẽ dùng ảnh ẩm thực dự phòng.



-- ==========================================================
-- V28: TẠO SUPABASE STORAGE CHO HÌNH ẢNH MÓN ĂN
-- Chạy 1 lần trong Supabase > SQL Editor > New Query > Run
-- ==========================================================

-- Tạo bucket public để ảnh có thể hiển thị trên app
insert into storage.buckets (id, name, public)
values ('menu-images', 'menu-images', true)
on conflict (id) do update set public = true;

-- Cho phép đọc ảnh công khai
drop policy if exists "Public read menu images" on storage.objects;
create policy "Public read menu images"
on storage.objects
for select
to public
using (bucket_id = 'menu-images');

-- Cho phép ứng dụng upload ảnh bằng publishable/anon key
drop policy if exists "Anon upload menu images" on storage.objects;
create policy "Anon upload menu images"
on storage.objects
for insert
to anon
with check (bucket_id = 'menu-images');

-- Cho phép ghi đè/cập nhật ảnh nếu cần
drop policy if exists "Anon update menu images" on storage.objects;
create policy "Anon update menu images"
on storage.objects
for update
to anon
using (bucket_id = 'menu-images')
with check (bucket_id = 'menu-images');

-- Cho phép xóa file trong bucket nếu sau này cần
drop policy if exists "Anon delete menu images" on storage.objects;
create policy "Anon delete menu images"
on storage.objects
for delete
to anon
using (bucket_id = 'menu-images');




